<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PayerEdi.Ingestion\PayerEdi.Ingestion.csproj" />
    <ProjectReference Include="..\PayerEdi.Pharmacy.Data\PayerEdi.Pharmacy.Data.csproj" />
  </ItemGroup>

</Project>